POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "anees_mon",
  "password": "1234567",
  "name": "Anees Mon",
  "gender": "male"
}

###
POST https://anees-twitter.herokuapp.com/login
Content-Type: application/json

{
  "username":"JoeBiden",
  "password":"biden@123"
}

###
GET http://localhost:3000/user/following
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1NTIyMzQ0OH0.oGCDptTrdm5JCOT093GhtdZHOX0hxm_ji2l5xKUqLC8
###

GET http://localhost:3000/user/followers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1NTIyMzQ0OH0.oGCDptTrdm5JCOT093GhtdZHOX0hxm_ji2l5xKUqLC8

###
GET https://anees-twitter.herokuapp.com/user/tweets/feed
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1NTIyMzQ0OH0.oGCDptTrdm5JCOT093GhtdZHOX0hxm_ji2l5xKUqLC8

###
GET http://localhost:3000/tweets/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1NTIyMzQ0OH0.oGCDptTrdm5JCOT093GhtdZHOX0hxm_ji2l5xKUqLC8

###
GET http://localhost:3000/tweets/1/likes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1NTIyMzQ0OH0.oGCDptTrdm5JCOT093GhtdZHOX0hxm_ji2l5xKUqLC8

###
GET http://localhost:3000/tweets/1/replies/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1NTIyMzQ0OH0.oGCDptTrdm5JCOT093GhtdZHOX0hxm_ji2l5xKUqLC8

###
GET http://localhost:3000/user/tweets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1NTIyMzQ0OH0.oGCDptTrdm5JCOT093GhtdZHOX0hxm_ji2l5xKUqLC8
